#make -f makefile_daw
#make clean -f makefile_daw

# Set the remove file command for your system used in the clean command
Rm = del

# Set the required Fortran compiler and associated flags
#F90 = ifort
#F90FLAGS =  -O3 /WARN:ALL /WARN:DECLARATIONS /STAND:F90 /TRACEBACK /CU
#F90LINKFLAGS = -O3  /WARN:ALL /WARN:DECLARATIONS /STAND:F90 /TRACEBACK /CU
#O = obj

F90 = gfortran
F90FLAGS = -O3 
F90LINKFLAGS = -O3 
O = o

# Templates for .f90->.o and .o -> executable
%.$O: %.f90
	$(F90)  $(F90FLAGS) -o $@ -c $<

%: %.$O
	$(F90) $(F90LINKFLAGS) -o $@ $^

OBJS = set_rk.$O  elemental_daw_mod_rk.$O 
daw_driver: $(OBJS)  daw_driver.$O
daw_driver.$O:  $(OBJS)



elemental_daw_mod_rk.$O: set_rk.$O
set_rk.$O:	


# Cleaning
.PHONY: clean
clean:
	# remove all files generated by the compiler
	# these are compiler dependent
	Rm -f *.$O *.d *.g90 *.mod
	# remove all executables
	Rm -f $(executables)
